Updates to resolve vulnerable dependencies of browser-sync
jh3y/gulp-boilerplate pull request #32
Opened 2018-11-07 17:29 UTC by Makskokhtenko

- update browser-sync

2018-11-07 17:57 UTC, jh3y requested changes
Hey @Makskokhtenko 👋 
Thanks for opening the PR. Would you mind bumping the version number to `4.1.6` and also updating `yarn.lock`. I haven't yet got round to automating tagging etc. so I can do that once merged.
Thanks 👍

2018-11-09 23:48 UTC, Makskokhtenko commented
nailed it

2018-11-12 09:50 UTC, jh3y approved these changes

2018-11-12 09:50 UTC, merged

2018-11-12 09:51 UTC, jh3y commented
Awesome! Thanks! 👍